### PR TITLE
A possible fix about functoria and pasteur

### PR DESCRIPTION
**Pull request by dinosaure**
With such [`config.ml`](https://github.com/dinosaure/pasteur/blob/32e3eb8780f7ec3232e19229c9b4ccd1eeacc32f/config.ml) which is a bit complex but the most interesting part is the `match_impl` about `docteur`, `functoria` raises the commented exception.

First at all, the exception is really cryptic according to what I try to do with `match_impl` - I don't see a link between "a cached configuration" and my `config.ml`. Secondly, I really don't know what I propose but if I return `None`, the given `config.ml` works perfectly. I'm not confident with this code-base but I really think that my usage is legitim.

/cc @Drup @TheLortex

### CODE REVIEW

**Comment by TheLortex** [comment]
In order to get more information, maybe you should look at the return value of `Cmdliner.Term.eval_peek_opts` when it fails. 
I'm not fully aware of the purpose of the context cache so that's something to dig out.

My guess is that simply returning `None` on failure won't help us in the process of fixing cryptic behaviors

**Comment by Drup** [comment]
I don't know much about the cache configuration aspects, so I can't help much here. Note that the next function over assumes that `peek` can return `None`, but it never happens before @dinosaure ... which makes me very confused.
It would help a lot to have a minimal test case.

@hannes is the original author, but I don't know if has changed much since.

(why the PR on a fork, btw ?)

**Comment by dinosaure** [comment]
> I don't know much about the cache configuration aspects, so I can't help much here. Note that the next function over assumes that peek can return None, but it never happens before @dinosaure ... which makes me very confused.
It would help a lot to have a minimal test case.

Ok, I will try to find a minimal case. I suspect `match_impl` but I'm not sure.

> (why the PR on a fork, btw ?)

It relies to what @TheLortex did on `mirage/mirage` if you want to replicate the situation - but then, yeah we should merge that into `mirage/mirage` :+1:.

**Comment by TheLortex** [comment]
The `mirage/mirage` main branch already has that configuration cache code (https://github.com/mirage/mirage/blob/master/lib/functoria/context_cache.ml#L67), is it possible to trigger the error there too ?

**Pull request closed without merging**
